server:
  port: 9001

spring:
  application:
    name: eventsourcing-actuating

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5434/nrf_actuating_event_sourcing
    username: nrf_actuating_event_sourcing
    password: DBLab1004**

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

multiplicationHost: http://${GATEWAY_HOST:localhost}:8000/api/v1

axon:
  serializer:
    general: xstream
  axonserver:
    servers: ${AXON_HOST:localhost}:8124

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
logging.level.io.wisoft.eventsourcing.actuating: debug
logging.level.org.axonframework: debug




