server:
  port: 9003

spring:
  application:
    name: eventsourcing-query
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5434/nrf_query
    username: nrf_query
    password: DBLab1004**
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


axon:
  serializer:
    general: xstream
  axonserver:
    servers: ${AXON_HOST:localhost}:8124

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    io.wisoft.eventsourcing.sensing: debug
    org.axonframework: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

